# Site settings
title: SoulBitGames
description: Where Every Bit Matters
# baseurl: "/"
url: "//soulbitgames.github.io"

# User settings
username: SoulBitGames
user_description: Where Every Bit Matters
user_title: Where Every Bit Matters
email: soulbitgames@gmail.com
repository: SoulBitGames/soulbitgames.com
twitter_username:
github_username:
gplus_username:

sass:
    sass_dir: _styles
    style: compressed

plugins:
  - jekyll-redirect-from

include:
  - _pages
